a:dailies-guide:
 - changed-files:
   - any-glob-to-any-file: source/channels/dailies-guide.ts
a:friendship-actions:
 - changed-files:
   - any-glob-to-any-file: source/channels/friendship-actions.ts
a:how-to-translate:
 - changed-files:
   - any-glob-to-any-file: source/channels/how-to-translate.ts
a:rules:
 - changed-files:
   - any-glob-to-any-file: source/channels/rules.ts
a:welcome:
 - changed-files:
   - any-glob-to-any-file: source/channels/welcome.ts
