name: Start delivery
on:
  workflow_dispatch:
    inputs:
      force:
        description: Force regeneration
        type: boolean
permissions:
  contents: write
jobs:
  delivery:
    name: Delivery
    runs-on: ubuntu-latest
    steps:
      - name: Create token
        id: create-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ vars.APPLICATION_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          owner: thatskyapplication
          repositories: Discord-Delivery
          permission-contents: write

      - uses: actions/checkout@v5
        with:
          token: ${{ steps.create-token.outputs.token }}

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Install Node.js
        uses: actions/setup-node@v6
        with:
          cache: pnpm
          node-version: 24

      - name: Install dependencies
        run: pnpm install

      - name: Build dependencies
        run: pnpm run build

      - name: Start delivery
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          FORCE: ${{ inputs.force }}
          WELCOME_CHANNEL_ID: ${{ vars.WELCOME_CHANNEL_ID }}
          RULES_CHANNEL_ID: ${{ vars.RULES_CHANNEL_ID }}
          FRIENDSHIP_ACTIONS_CHANNEL_ID: ${{ vars.FRIENDSHIP_ACTIONS_CHANNEL_ID }}
          UPDATING_DAILY_GUIDES_CHANNEL_ID: ${{ vars.UPDATING_DAILY_GUIDES_CHANNEL_ID }}
          HOW_TO_TRANSLATE_CHANNEL_ID: ${{ vars.HOW_TO_TRANSLATE_CHANNEL_ID }}
        run: pnpm run start

      - name: Update message ids
        run: |
          git config user.name thatskyapplication[bot]
          git config user.email "${{ vars.APPLICATION_USER_ID }}+thatskyapplication[bot]@users.noreply.github.com"
          git pull
          git add ./source/message-ids.json

          if ! git diff-index --quiet HEAD; then
            git commit -m "chore: Update message ids"
            git push
          else
            echo "No changes to commit."
          fi
        env:
          GITHUB_TOKEN: ${{ steps.create-token.outputs.token }}
